name: "Release Action"

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump tag version
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch

      - name: Fetch tag
        if: steps.tag.outputs.new_tag != ''
        run: git fetch origin tag ${{ steps.tag.outputs.new_tag }}

      - name: Create source zip
        if: steps.tag.outputs.new_tag != ''
        run: git archive -o source.zip ${{ steps.tag.outputs.new_tag }}

      - name: Create GitHub Release
        if: steps.tag.outputs.new_tag != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          files: source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
